  variable server_role {}
  variable subnet_id {}
  variable vm_size {}
  variable publisher {}
  variable offer {}
  variable sku {}
  variable version {}
  variable computer_name {}
  variable admin_username {}
  variable admin_password {}
  variable StudentId {}
  variable azure_region {}
